version: '3'
services:
  rstudio:
    image: rocker/rstudio
    environment:
      - PASSWORD=eiSaez0ohZ8ahf0a
    ports:
      - "8787:8787"
    volumes:
      - $HOME/Downloads/minicursoR:/home/rstudio/
